{% set name = "hussh" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hussh-{{ version }}.tar.gz
  sha256: 3cd93070cc4d7865c17f3ec43f6cc62ff4fecc943b9acc13df798f6e96706494

build:
  skip: true  # [py<38]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - make
    - perl  # [win]
  host:
    - python
    - maturin >=1.5,<2.0
    - pip
  run:
    - python

test:
  imports:
    - hussh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JacobCallahan/Hussh
  summary: Client-side ssh library that offers low level performance through a high level interface
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
